# Generated by Django 6.0.4 on 2026-04-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Principal')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoría (Marca)',
                'verbose_name_plural': '1. Categorías (Marcas)',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Logo CleverFix')),
                ('phone', models.CharField(default='686 178 0903', max_length=20, verbose_name='Teléfono')),
                ('site_name', models.CharField(default='CleverFix', max_length=50)),
            ],
            options={
                'verbose_name': '0. Configuración',
                'verbose_name_plural': '0. Configuración',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Dispositivo')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='store.category', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo',
                'verbose_name_plural': '2. Tipos de Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modelo / Variante Exacta')),
                ('slug', models.SlugField()),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='store.devicetype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Modelo Exacto',
                'verbose_name_plural': '3. Modelos Exactos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Refacción')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción para el carrito')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Foto del Producto')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Existencia')),
                ('active', models.BooleanField(default=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.devicemodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': '4. Productos Finales',
            },
        ),
    ]
