# Generated by Django 6.0.4 on 2026-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Token de Autenticación'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='¿Verificado?'),
        ),
    ]
