# Generated by Django 6.0.4 on 2026-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customerprofile_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Escribe el color manualmente (ej: Negro Mate, Blanco, etc.)', max_length=50, null=True, verbose_name='Color / Variante'),
        ),
    ]
