# Generated by Django 6.0.4 on 2026-04-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Escribe el color manualmente (ej: Azul Sierra, Negro Mate)', max_length=50, null=True, verbose_name='Color / Variante'),
        ),
    ]
